### PR TITLE
Updated default.settings.php

### PR DESCRIPTION
**Pull request by navneet0693**
1. Updated default.settings.php as per Drupal 9.
2. Added pre-configured settings.local.php.
3. Updated install script.

### CODE REVIEW

**Review by tbsiqueira — APPROVED** [review]

**Review by Ressinel — COMMENTED** [review]
@navneet0693 Why do we need `settings.local.php` in the repo?

**Comment by navneet0693** [comment]
@Ressinel So that we can ship with prebuilt settings.local.php for developers for the local environment.

**Comment by Ressinel** [comment]
@navneet0693 I would suggest adding `default.settings.local.php` instead of `settings.local.php` What do you think about it?

**Comment by navneet0693** [comment]
> @navneet0693 I would suggest adding `default.settings.local.php` instead of `settings.local.php` What do you think about it?

My idea is more of our shipping a settings.local.php by default instead. Our default.settings.php will also be copied and converted to settings.php during the installation process. If we add `example.settings.local.php` instead, I will have to add a step to copy it. Also, we don't add a step, then it will be on developers if they pay attention to it. We want to ship a ready environment by default with minimal actions needed.

**Pull request merged**
